import type {
  Academy,
  LearningResource,
  SafetyZone,
  School,
  TransitStop
} from "@/lib/types";

export const schools: School[] = [
  {
    id: "school-daechi",
    neisSchoolId: "B100000001",
    educationOfficeCode: "B10",
    name: "대치초등학교",
    kind: "초등학교",
    region: "서울특별시",
    district: "강남구",
    address: "서울특별시 강남구 대치동 999",
    studentCount: 820,
    publicSupportSlots: 72,
    coordinate: { lat: 37.4942, lng: 127.0635 }
  },
  {
    id: "school-haemil",
    neisSchoolId: "I100000001",
    educationOfficeCode: "I10",
    name: "해밀초등학교",
    kind: "초등학교",
    region: "세종특별자치시",
    district: "해밀동",
    address: "세종특별자치시 해밀1로 73",
    studentCount: 640,
    publicSupportSlots: 38,
    coordinate: { lat: 36.5256, lng: 127.2684 }
  },
  {
    id: "school-bonghwa",
    neisSchoolId: "R100000001",
    educationOfficeCode: "R10",
    name: "석포초등학교",
    kind: "초등학교",
    region: "경상북도",
    district: "봉화군",
    address: "경상북도 봉화군 석포면 석포로1길 33",
    studentCount: 52,
    publicSupportSlots: 8,
    coordinate: { lat: 37.0463, lng: 129.0639 }
  },
  {
    id: "school-suwon",
    neisSchoolId: "J100000001",
    educationOfficeCode: "J10",
    name: "광교중학교",
    kind: "중학교",
    region: "경기도",
    district: "수원시",
    address: "경기도 수원시 영통구 광교중앙로 140",
    studentCount: 760,
    publicSupportSlots: 44,
    coordinate: { lat: 37.2892, lng: 127.0517 }
  }
];

export const academies: Academy[] = [
  {
    id: "academy-d-01",
    neisAcademyId: "B10-A001",
    educationOfficeCode: "B10",
    name: "대치수학전략학원",
    academyType: "학원",
    realm: "입시.검정 및 보습",
    group: "학습/입시",
    course: "보습",
    subject: "수학",
    capacity: 160,
    monthlyFee: 540000,
    feeDisclosed: true,
    address: "서울특별시 강남구 도곡로 430",
    status: "등록",
    establishedAt: "2017-03-12",
    closedAt: null,
    sourceUpdatedAt: "2026-03-18",
    coordinate: { lat: 37.4961, lng: 127.0616 }
  },
  {
    id: "academy-d-02",
    neisAcademyId: "B10-A002",
    educationOfficeCode: "B10",
    name: "한뜻영어교습소",
    academyType: "교습소",
    realm: "외국어",
    group: "외국어",
    course: "영어",
    subject: "영어독해",
    capacity: 24,
    monthlyFee: 360000,
    feeDisclosed: true,
    address: "서울특별시 강남구 삼성로 212",
    status: "등록",
    establishedAt: "2021-09-01",
    closedAt: null,
    sourceUpdatedAt: "2026-03-18",
    coordinate: { lat: 37.4932, lng: 127.0664 }
  },
  {
    id: "academy-d-03",
    neisAcademyId: "B10-A003",
    educationOfficeCode: "B10",
    name: "개념논술랩",
    academyType: "학원",
    realm: "입시.검정 및 보습",
    group: "사고력/논술",
    course: "논술",
    subject: "독서논술",
    capacity: 80,
    monthlyFee: 420000,
    feeDisclosed: true,
    address: "서울특별시 강남구 남부순환로 2912",
    status: "등록",
    establishedAt: "2019-05-10",
    closedAt: null,
    sourceUpdatedAt: "2026-03-18",
    coordinate: { lat: 37.4918, lng: 127.0597 }
  },
  {
    id: "academy-d-04",
    neisAcademyId: "B10-A004",
    educationOfficeCode: "B10",
    name: "코드브릿지 대치",
    academyType: "학원",
    realm: "정보",
    group: "코딩/IT",
    course: "컴퓨터",
    subject: "파이썬",
    capacity: 64,
    monthlyFee: 460000,
    feeDisclosed: true,
    address: "서울특별시 강남구 역삼로 421",
    status: "등록",
    establishedAt: "2022-01-14",
    closedAt: null,
    sourceUpdatedAt: "2026-03-18",
    coordinate: { lat: 37.4985, lng: 127.0649 }
  },
  {
    id: "academy-d-05",
    neisAcademyId: "B10-A005",
    educationOfficeCode: "B10",
    name: "대치아트스튜디오",
    academyType: "학원",
    realm: "예능",
    group: "예체능",
    course: "미술",
    subject: "입시미술",
    capacity: 70,
    monthlyFee: 510000,
    feeDisclosed: true,
    address: "서울특별시 강남구 선릉로 324",
    status: "등록",
    establishedAt: "2016-11-09",
    closedAt: null,
    sourceUpdatedAt: "2026-03-18",
    coordinate: { lat: 37.4926, lng: 127.0562 }
  },
  {
    id: "academy-d-06",
    neisAcademyId: "B10-A006",
    educationOfficeCode: "B10",
    name: "열린독서실",
    academyType: "독서실",
    realm: "독서실",
    group: "독서실",
    course: "독서실",
    subject: "자율학습",
    capacity: 110,
    monthlyFee: 180000,
    feeDisclosed: true,
    address: "서울특별시 강남구 삼성로 155",
    status: "등록",
    establishedAt: "2013-06-30",
    closedAt: null,
    sourceUpdatedAt: "2026-03-18",
    coordinate: { lat: 37.4908, lng: 127.0639 }
  },
  {
    id: "academy-h-01",
    neisAcademyId: "I10-A001",
    educationOfficeCode: "I10",
    name: "해밀수학나무",
    academyType: "교습소",
    realm: "보습",
    group: "학습/입시",
    course: "보습",
    subject: "초등수학",
    capacity: 28,
    monthlyFee: 230000,
    feeDisclosed: true,
    address: "세종특별자치시 해밀동 331",
    status: "등록",
    establishedAt: "2024-02-01",
    closedAt: null,
    sourceUpdatedAt: "2026-03-16",
    coordinate: { lat: 36.5239, lng: 127.2661 }
  },
  {
    id: "academy-h-02",
    neisAcademyId: "I10-A002",
    educationOfficeCode: "I10",
    name: "세종영어숲",
    academyType: "학원",
    realm: "외국어",
    group: "외국어",
    course: "영어",
    subject: "회화",
    capacity: 72,
    monthlyFee: 280000,
    feeDisclosed: true,
    address: "세종특별자치시 해밀3로 12",
    status: "등록",
    establishedAt: "2023-08-21",
    closedAt: null,
    sourceUpdatedAt: "2026-03-16",
    coordinate: { lat: 36.5277, lng: 127.2711 }
  },
  {
    id: "academy-h-03",
    neisAcademyId: "I10-A003",
    educationOfficeCode: "I10",
    name: "해밀피아노",
    academyType: "교습소",
    realm: "예능",
    group: "예체능",
    course: "음악",
    subject: "피아노",
    capacity: 36,
    monthlyFee: 190000,
    feeDisclosed: true,
    address: "세종특별자치시 해밀2로 20",
    status: "등록",
    establishedAt: "2022-03-22",
    closedAt: null,
    sourceUpdatedAt: "2026-03-16",
    coordinate: { lat: 36.5209, lng: 127.2696 }
  },
  {
    id: "academy-h-04",
    neisAcademyId: "I10-A004",
    educationOfficeCode: "I10",
    name: "새움코딩교실",
    academyType: "학원",
    realm: "정보",
    group: "코딩/IT",
    course: "컴퓨터",
    subject: "블록코딩",
    capacity: 48,
    monthlyFee: null,
    feeDisclosed: false,
    address: "세종특별자치시 해밀동 604",
    status: "등록",
    establishedAt: "2025-01-15",
    closedAt: null,
    sourceUpdatedAt: "2026-03-16",
    coordinate: { lat: 36.5291, lng: 127.2633 }
  },
  {
    id: "academy-b-01",
    neisAcademyId: "R10-A001",
    educationOfficeCode: "R10",
    name: "석포보습교습소",
    academyType: "교습소",
    realm: "보습",
    group: "학습/입시",
    course: "보습",
    subject: "국수사과",
    capacity: 12,
    monthlyFee: 150000,
    feeDisclosed: true,
    address: "경상북도 봉화군 석포면 석포리 376",
    status: "등록",
    establishedAt: "2020-04-01",
    closedAt: null,
    sourceUpdatedAt: "2026-02-11",
    coordinate: { lat: 37.0478, lng: 129.0598 }
  },
  {
    id: "academy-b-02",
    neisAcademyId: "R10-A002",
    educationOfficeCode: "R10",
    name: "석포피아노교습소",
    academyType: "교습소",
    realm: "예능",
    group: "예체능",
    course: "음악",
    subject: "피아노",
    capacity: 10,
    monthlyFee: 120000,
    feeDisclosed: true,
    address: "경상북도 봉화군 석포면 석포로 24",
    status: "휴원",
    establishedAt: "2018-05-11",
    closedAt: null,
    sourceUpdatedAt: "2026-02-11",
    coordinate: { lat: 37.0426, lng: 129.0655 }
  },
  {
    id: "academy-s-01",
    neisAcademyId: "J10-A001",
    educationOfficeCode: "J10",
    name: "광교수학센터",
    academyType: "학원",
    realm: "입시.검정 및 보습",
    group: "학습/입시",
    course: "보습",
    subject: "중등수학",
    capacity: 110,
    monthlyFee: 340000,
    feeDisclosed: true,
    address: "경기도 수원시 영통구 광교중앙로 145",
    status: "등록",
    establishedAt: "2021-02-24",
    closedAt: null,
    sourceUpdatedAt: "2026-03-19",
    coordinate: { lat: 37.2907, lng: 127.0534 }
  },
  {
    id: "academy-s-02",
    neisAcademyId: "J10-A002",
    educationOfficeCode: "J10",
    name: "광교영어라운지",
    academyType: "학원",
    realm: "외국어",
    group: "외국어",
    course: "영어",
    subject: "내신영어",
    capacity: 88,
    monthlyFee: 310000,
    feeDisclosed: true,
    address: "경기도 수원시 영통구 센트럴타운로 85",
    status: "등록",
    establishedAt: "2020-10-07",
    closedAt: null,
    sourceUpdatedAt: "2026-03-19",
    coordinate: { lat: 37.2878, lng: 127.0498 }
  },
  {
    id: "academy-s-03",
    neisAcademyId: "J10-A003",
    educationOfficeCode: "J10",
    name: "미래융합코딩학원",
    academyType: "학원",
    realm: "정보",
    group: "코딩/IT",
    course: "컴퓨터",
    subject: "앱개발",
    capacity: 54,
    monthlyFee: 390000,
    feeDisclosed: true,
    address: "경기도 수원시 영통구 도청로 30",
    status: "등록",
    establishedAt: "2023-03-02",
    closedAt: null,
    sourceUpdatedAt: "2026-03-19",
    coordinate: { lat: 37.2918, lng: 127.0474 }
  },
  {
    id: "academy-s-04",
    neisAcademyId: "J10-A004",
    educationOfficeCode: "J10",
    name: "광교독서실",
    academyType: "독서실",
    realm: "독서실",
    group: "독서실",
    course: "독서실",
    subject: "자율학습",
    capacity: 96,
    monthlyFee: 160000,
    feeDisclosed: true,
    address: "경기도 수원시 영통구 대학로 16",
    status: "폐원",
    establishedAt: "2019-01-03",
    closedAt: "2025-12-31",
    sourceUpdatedAt: "2026-03-19",
    coordinate: { lat: 37.2853, lng: 127.0542 }
  }
];

export const learningResources: LearningResource[] = [
  {
    id: "res-d-01",
    sourceKey: "library-gangnam-daechi",
    name: "못골도서관",
    type: "LIBRARY",
    region: "서울특별시",
    district: "강남구",
    address: "서울특별시 강남구 자곡로 116",
    capacity: 190,
    cost: 0,
    operatingHours: "09:00-22:00",
    target: "초중고",
    phone: "02-0000-0000",
    homepage: "https://library.gangnam.go.kr",
    tags: ["열람실", "도서", "자율학습"],
    coordinate: { lat: 37.4863, lng: 127.1046 }
  },
  {
    id: "res-d-02",
    sourceKey: "program-gangnam-after",
    name: "강남 방과후 학습클리닉",
    type: "PUBLIC_PROGRAM",
    region: "서울특별시",
    district: "강남구",
    address: "서울특별시 강남구 학동로 426",
    capacity: 80,
    cost: 0,
    operatingHours: "평일 16:00-19:00",
    target: "초중",
    phone: "02-0000-0001",
    homepage: "https://www.gangnam.go.kr",
    tags: ["수학", "영어", "멘토링"],
    coordinate: { lat: 37.5172, lng: 127.0473 }
  },
  {
    id: "res-h-01",
    sourceKey: "library-haemil",
    name: "해밀동 복합커뮤니티센터 도서관",
    type: "LIBRARY",
    region: "세종특별자치시",
    district: "해밀동",
    address: "세종특별자치시 해밀3로 49",
    capacity: 120,
    cost: 0,
    operatingHours: "09:00-18:00",
    target: "전체",
    phone: "044-000-0000",
    homepage: "https://www.sejong.go.kr",
    tags: ["도서", "열람", "초등"],
    coordinate: { lat: 36.5265, lng: 127.2747 }
  },
  {
    id: "res-h-02",
    sourceKey: "counsel-haemil",
    name: "세종 청소년상담복지센터",
    type: "COUNSELING_CENTER",
    region: "세종특별자치시",
    district: "해밀동",
    address: "세종특별자치시 조치원읍 새내로 108",
    capacity: 40,
    cost: 0,
    operatingHours: "09:00-18:00",
    target: "청소년",
    phone: "044-000-1388",
    homepage: "https://www.1388.go.kr",
    tags: ["상담", "심리검사"],
    coordinate: { lat: 36.6015, lng: 127.2981 }
  },
  {
    id: "res-b-01",
    sourceKey: "library-bonghwa",
    name: "봉화군립도서관",
    type: "LIBRARY",
    region: "경상북도",
    district: "봉화군",
    address: "경상북도 봉화군 봉화읍 내성로 82",
    capacity: 90,
    cost: 0,
    operatingHours: "09:00-18:00",
    target: "전체",
    phone: "054-000-0000",
    homepage: "https://www.bonghwa.go.kr",
    tags: ["도서", "열람"],
    coordinate: { lat: 36.8936, lng: 128.7329 }
  },
  {
    id: "res-s-01",
    sourceKey: "library-gwanggyo",
    name: "광교홍재도서관",
    type: "LIBRARY",
    region: "경기도",
    district: "수원시",
    address: "경기도 수원시 영통구 대학로 88",
    capacity: 320,
    cost: 0,
    operatingHours: "09:00-22:00",
    target: "전체",
    phone: "031-000-0000",
    homepage: "https://www.suwonlib.go.kr",
    tags: ["열람실", "도서", "청소년"],
    coordinate: { lat: 37.2939, lng: 127.0478 }
  },
  {
    id: "res-s-02",
    sourceKey: "youth-gwanggyo",
    name: "수원청소년문화센터 광교분소",
    type: "YOUTH_CENTER",
    region: "경기도",
    district: "수원시",
    address: "경기도 수원시 영통구 도청로 30",
    capacity: 110,
    cost: 0,
    operatingHours: "10:00-20:00",
    target: "청소년",
    phone: "031-000-1388",
    homepage: "https://www.syf.or.kr",
    tags: ["진로", "상담", "멘토링"],
    coordinate: { lat: 37.2914, lng: 127.0464 }
  }
];

export const transitStops: TransitStop[] = [
  {
    id: "stop-d-01",
    nodeId: "B1001",
    name: "대치역",
    cityCode: "11",
    coordinate: { lat: 37.4945, lng: 127.0632 }
  },
  {
    id: "stop-d-02",
    nodeId: "B1002",
    name: "대치초등학교",
    cityCode: "11",
    coordinate: { lat: 37.4931, lng: 127.061 }
  },
  {
    id: "stop-h-01",
    nodeId: "I1001",
    name: "해밀초등학교",
    cityCode: "36",
    coordinate: { lat: 36.525, lng: 127.2688 }
  },
  {
    id: "stop-b-01",
    nodeId: "R1001",
    name: "석포면사무소",
    cityCode: "47",
    coordinate: { lat: 37.0435, lng: 129.0612 }
  },
  {
    id: "stop-s-01",
    nodeId: "J1001",
    name: "광교중앙역",
    cityCode: "31",
    coordinate: { lat: 37.2887, lng: 127.051 }
  },
  {
    id: "stop-s-02",
    nodeId: "J1002",
    name: "광교중학교",
    cityCode: "31",
    coordinate: { lat: 37.2891, lng: 127.0532 }
  }
];

export const safetyZones: SafetyZone[] = [
  {
    id: "zone-d-01",
    sourceKey: "schoolzone-daechi",
    facilityName: "대치초등학교 어린이보호구역",
    facilityType: "초등학교",
    cctvInstalled: true,
    cctvCount: 7,
    roadWidth: "8~15",
    coordinate: { lat: 37.4942, lng: 127.0635 }
  },
  {
    id: "zone-h-01",
    sourceKey: "schoolzone-haemil",
    facilityName: "해밀초등학교 어린이보호구역",
    facilityType: "초등학교",
    cctvInstalled: true,
    cctvCount: 2,
    roadWidth: "27",
    coordinate: { lat: 36.5256, lng: 127.2684 }
  },
  {
    id: "zone-b-01",
    sourceKey: "schoolzone-seokpo",
    facilityName: "석포초등학교 어린이보호구역",
    facilityType: "초등학교",
    cctvInstalled: true,
    cctvCount: 1,
    roadWidth: "6",
    coordinate: { lat: 37.0463, lng: 129.0639 }
  },
  {
    id: "zone-s-01",
    sourceKey: "schoolzone-gwanggyo",
    facilityName: "광교중학교 주변 보호구역",
    facilityType: "중학교",
    cctvInstalled: true,
    cctvCount: 3,
    roadWidth: "10~20",
    coordinate: { lat: 37.2892, lng: 127.0517 }
  }
];
