services:
  postgres:
    image: kartoza/postgis:15-3.4
    container_name: hakwonnono-db
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: hakwonnono
      POSTGRES_PASSWORD: hakwonnono
      POSTGRES_DB: hakwonnono
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
