import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: ["class"],
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    container: {
      center: true,
      padding: "1rem",
      screens: { "2xl": "1280px" },
    },
    extend: {
      colors: {
        // shadcn 토큰
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        // ── Primary scale (Crail Orange #D97757) ──
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
          50: "#FBF4EF",
          100: "#F6E4D8",
          200: "#EFC9B0",
          300: "#E5A887",
          400: "#DD8B69",
          500: "#D97757",
          600: "#C5613F",
          700: "#A24A2D",
          800: "#7A381F",
          900: "#502715",
        },
        // ── Secondary scale (Stone-warm) ──
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
          50: "#FAF9F5",
          100: "#F5F4ED",
          200: "#EFEEE5",
          300: "#E2E0D4",
          400: "#C8C5B7",
          500: "#9A988C",
          600: "#6B6862",
          700: "#4A4842",
          800: "#2F2D29",
          900: "#1F1E1D",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        // ── Accent (Tan/Gold) ──
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
          50: "#FAF6EE",
          100: "#F2E8D2",
          200: "#E5D2A6",
          300: "#D4B872",
          400: "#C29E48",
          500: "#A78232",
          600: "#876727",
          700: "#5F4A1D",
          800: "#3D3013",
          900: "#221B0A",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        // ── Status scales (호환용) ──
        success: {
          DEFAULT: "hsl(var(--success))",
          foreground: "hsl(var(--success-foreground))",
          50: "#F0FDF4",
          100: "#DCFCE7",
          200: "#BBF7D0",
          400: "#4ADE80",
          500: "#22C55E",
          600: "#16A34A",
          700: "#15803D",
        },
        warning: {
          DEFAULT: "hsl(var(--warning))",
          foreground: "hsl(var(--warning-foreground))",
          50: "#FFFBEB",
          100: "#FEF3C7",
          200: "#FDE68A",
          400: "#FBBF24",
          500: "#F59E0B",
          600: "#D97706",
          700: "#B45309",
        },
        error: {
          50: "#FEF2F2",
          100: "#FEE2E2",
          200: "#FECACA",
          400: "#F87171",
          500: "#EF4444",
          600: "#DC2626",
          700: "#B91C1C",
        },
        // 분야 토큰 (지도/차트 공용)
        realm: {
          study: "hsl(var(--realm-study))",
          art: "hsl(var(--realm-art))",
          lang: "hsl(var(--realm-lang))",
          job: "hsl(var(--realm-job))",
          comprehensive: "hsl(var(--realm-comprehensive))",
          reading: "hsl(var(--realm-reading))",
          etc: "hsl(var(--realm-etc))",
          it: "hsl(var(--realm-it))",
          thinking: "hsl(var(--realm-thinking))",
          special: "hsl(var(--realm-special))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
        "4xl": "2rem",
      },
      fontFamily: {
        sans: ["Inter", "Pretendard Variable", "Pretendard", "ui-sans-serif", "system-ui"],
        serif: ["Source Serif Pro", "Tiempos Text", "ui-serif", "Georgia", "serif"],
        mono: ["ui-monospace", "SFMono-Regular", "Menlo", "monospace"],
      },
      fontSize: {
        display: ["2.5rem", { lineHeight: "2.75rem", letterSpacing: "-0.02em", fontWeight: "600" }],
        "heading-lg": ["1.75rem", { lineHeight: "2.125rem", letterSpacing: "-0.015em", fontWeight: "600" }],
        heading: ["1.375rem", { lineHeight: "1.875rem", letterSpacing: "-0.01em", fontWeight: "600" }],
        "heading-sm": ["1.125rem", { lineHeight: "1.5rem", letterSpacing: "-0.005em", fontWeight: "600" }],
        "body-lg": ["1rem", { lineHeight: "1.625rem" }],
        body: ["0.9375rem", { lineHeight: "1.5rem" }],
        "body-sm": ["0.8125rem", { lineHeight: "1.25rem" }],
        caption: ["0.75rem", { lineHeight: "1.125rem" }],
        overline: ["0.6875rem", { lineHeight: "1rem", letterSpacing: "0.05em", fontWeight: "600" }],
      },
      boxShadow: {
        subtle: "0 1px 2px 0 rgb(0 0 0 / 0.04)",
        soft: "0 1px 3px 0 rgb(0 0 0 / 0.06), 0 1px 2px -1px rgb(0 0 0 / 0.06)",
        raised: "0 2px 8px -2px rgb(0 0 0 / 0.08)",
        overlay: "0 8px 24px -8px rgb(0 0 0 / 0.12), 0 4px 8px -4px rgb(0 0 0 / 0.06)",
        modal: "0 16px 40px -8px rgb(0 0 0 / 0.16), 0 8px 16px -8px rgb(0 0 0 / 0.08)",
        card: "0 1px 2px 0 rgb(0 0 0 / 0.04), 0 2px 6px -2px rgb(0 0 0 / 0.06)",
        "card-hover": "0 4px 16px -4px rgb(0 0 0 / 0.1), 0 2px 8px -4px rgb(0 0 0 / 0.04)",
      },
      spacing: {
        "4.5": "1.125rem",
        "13": "3.25rem",
        "15": "3.75rem",
        "18": "4.5rem",
        "22": "5.5rem",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        shimmer: {
          "0%": { transform: "translateX(-100%)" },
          "100%": { transform: "translateX(100%)" },
        },
        "count-up": {
          "0%": { opacity: "0", transform: "translateY(4px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        shimmer: "shimmer 2s infinite linear",
        "count-up": "count-up 0.4s ease-out",
        "slide-in-right": "slide-in-right 0.25s cubic-bezier(0.16, 1, 0.3, 1)",
        "slide-up": "slide-up 0.35s cubic-bezier(0.16, 1, 0.3, 1)",
        "fade-in": "fade-in 0.15s ease-out",
        "fade-in-up": "fade-in-up 0.2s cubic-bezier(0.16, 1, 0.3, 1)",
      },
      transitionTimingFunction: {
        "ease-spring": "cubic-bezier(0.16, 1, 0.3, 1)",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
export default config;
